Name:           ros-hydro-hironx-tutorial
Version:        0.1.2
Release:        0%{?dist}
Summary:        ROS hironx_tutorial package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/hironx_tutorial
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-hironx-ros-bridge
Requires:       ros-hydro-leap-motion
Requires:       ros-hydro-moveit-commander
Requires:       ros-hydro-nextage-ros-bridge
Requires:       ros-hydro-rospy
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-leap-motion
BuildRequires:  ros-hydro-moveit-commander
BuildRequires:  ros-hydro-nextage-ros-bridge
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-tf

%description
Sample / demo / tutorial programs for Hiro and NEXTAGE OPEN (NXO) robot by
Kawada Industries. All sample code that works on Hiro robot should work also on
NEXTAGE OPEN. The opposite is, however, not always true (e.g. gripper operation
is different in NXO).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Aug 26 2014 Isaac Saito <dev@opensource-robotics.tokyo.jp> - 0.1.2-0
- Autogenerated by Bloom

